export const EVENTS = [
  {
    name: "Cosmic Deli",
    slug: "cosmic-deli",
    type: "technical",
    image: "/images/work-items/work-item-1.jpg",
    registerUrl: "#",
    rulebookUrl: "#",
  },
  {
    name: "Skull Pop 7",
    slug: "skull-pop-7",
    type: "technical",
    image: "/images/work-items/work-item-2.jpg",
    registerUrl: "#",
    rulebookUrl: "#",
  },
  {
    name: "Room 404",
    slug: "room-404",
    type: "fun",
    image: "/images/work-items/work-item-3.jpg",
    registerUrl: "#",
    rulebookUrl: "#",
  },
  {
    name: "Red Dot Mission",
    slug: "red-dot-mission",
    type: "fun",
    image: "/images/work-items/work-item-4.jpg",
    registerUrl: "#",
    rulebookUrl: "#",
  },
  // literary events
  {
    name: "Fate brings your own words",
    slug: "fate-brings-your-own-words",
    type: "literary",
    image: "/images/work-items/work-item-5.jpg",
    registerUrl: "https://forms.gle/MSXMK9ByxoYvZaXn8",
    rulebookUrl: "#",
  },
  {
    name: "Trivia Trek",
    slug: "trivia-trek",
    type: "literary",
    image: "/images/work-items/work-item-6.jpg",
    registerUrl: "https://forms.gle/q8L2ua5eW3LepkJi9",
    rulebookUrl: "#",
  },
  {
    name: "Youth Parliament",
    slug: "youth-parliament",
    type: "literary",
    image: "/images/work-items/work-item-6.jpg",
    registerUrl: "https://forms.gle/ko1LGKF87QcHXcUXA",
    rulebookUrl: "#",
  },
  {
    name: "Identity Insights",
    slug: "identity-insights",
    type: "literary",
    image: "/images/work-items/work-item-5.jpg",
    registerUrl: "https://forms.gle/95i9kfEQe5jTY6WQ8",
    rulebookUrl: "#",
  },
  {
    name: "Brainy Grid",
    slug: "brainy-grid",
    type: "literary",
    image: "/images/work-items/work-item-5.jpg",
    registerUrl: " https://docs.google.com/forms/d/e/1FAIpQLSf23Zhn-3_6D1lxYLUi2ZcUXwlZ6H1ZmZay4iIki1q7vDj_Nw/viewform?usp=dialog",
    rulebookUrl: "#",
  },
{
    name: "Spell bee",
    slug: "spell-bee",
    type: "literary",
    image: "/images/work-items/work-item-6.jpg",
    registerUrl: "https://forms.gle/DbsWx74b3efq1jQWA",
    rulebookUrl: "#",
  },
  {
    name: "Debate",
    slug: "debate",
    type: "literary",
    image: "/images/work-items/work-item-6.jpg",
    registerUrl: "https://forms.gle/x23xuTaaVYTKBC4Z7",
    rulebookUrl: "#",
  },
   {
    name: "Finger Dab",
    slug: "finger-dab",
    type: "literary",
    image: "/images/work-items/work-item-6.jpg",
    registerUrl: " https://forms.gle/kxgTpkanLaeBe86D6",
    rulebookUrl: "#",
  },
  {
    name: "PPDT",
    slug: "ppdt",
    type: "literary",
    image: "/images/work-items/work-item-6.jpg",
    registerUrl: "https://forms.gle/KdkM5spoVVaQC4Ln8",
    rulebookUrl: "#",
  },
  {
    name: "Visual Verses",
    slug: "visual-verses",
    type: "literary",
    image: "/images/work-items/work-item-6.jpg",
    registerUrl: "https://forms.gle/cf7XsTCpfjBv4gpB9",
    rulebookUrl: "#",
  },
  {
    name: "Naqaab",
    slug: "naqaab",
    type: "literary",
    image: "/images/work-items/work-item-6.jpg",
    registerUrl: " https://forms.gle/n6fPLvueHpjH3tyr5",
    rulebookUrl: "#",
  },
  //literary events end
  {
    name: "Soft Noise",
    slug: "soft-noise",
    type: "cultural",
    image: "/images/work-items/work-item-7.jpg",
    registerUrl: "#",
    rulebookUrl: "#",
  },
  {
    name: "Cloud Valley Echo",
    slug: "cloud-valley-echo",
    type: "cultural",
    image: "/images/work-items/work-item-8.jpg",
    registerUrl: "#",
    rulebookUrl: "#",
  },
];

export const EVENT_TYPES = [
  { key: "technical", label: "Technical Events" },
  { key: "fun", label: "Fun Events" },
  { key: "literary", label: "Literary Events" },
  { key: "cultural", label: "Cultural Events" },
];
